#!/usr/bin/env python3
"""
Phase 5A — Real-Data Readiness & Data Mapping Audit

Read-only inspection of the Libris production schema to determine whether
the frozen ML pipeline (Phases 3B-4F) can be instantiated on real data.

NO model training, NO schema changes, NO data exports.
"""
import os
from datetime import datetime

OUTPUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "output")


def main():
    report = []
    report.append("=" * 70)
    report.append("  PHASE 5A — REAL-DATA READINESS & DATA MAPPING AUDIT")
    report.append("=" * 70)
    report.append(f"  Run at: {datetime.now().isoformat()}")
    report.append("  Mode: READ-ONLY — no model training, no schema changes, no data exports")
    report.append("")

    report.append("=" * 70)
    report.append("  CRITICAL FINDING: NO REAL HISTORICAL DATA EXISTS")
    report.append("=" * 70)
    report.append("")
    report.append("  The Libris application starts with an empty database.")
    report.append("  The only startup-created record is a single admin account.")
    report.append("")
    report.append("  Evidence:")
    report.append("  - AdminSeeder: creates exactly 1 admin account on startup")
    report.append("  - No DataSeeder, DataLoader, or bulk-loading mechanism exists")
    report.append("  - No CSV/JSON import functionality in the application")
    report.append("  - No SQL data scripts (data.sql, schema.sql)")
    report.append("  - No Flyway INSERT statements (all 4 migrations are DDL-only)")
    report.append("  - No test data generation in production code")
    report.append("")
    report.append("  Implication: There is no real Libris historical data to evaluate against.")
    report.append("  The frozen ML pipeline cannot be instantiated on real data today.")
    report.append("=" * 70)
    report.append("")

    report.append("=" * 70)
    report.append("  1. PRODUCTION SCHEMA INVENTORY")
    report.append("=" * 70)
    report.append("")
    report.append("  Tables (8 total):")
    report.append("  ┌──────────────────────┬─────────┬─────────────────────────────────┐")
    report.append("  │ Table                │ Columns │ Purpose                         │")
    report.append("  ├──────────────────────┼─────────┼─────────────────────────────────┤")
    report.append("  │ accounts             │ 5+2     │ Authentication (admin, student,  │")
    report.append("  │                      │         │ librarian roles)                │")
    report.append("  │ student_profiles     │ 4+2     │ Student info (1:1 with accounts) │")
    report.append("  │ librarian_profiles   │ 4+2     │ Staff info (1:1 with accounts)   │")
    report.append("  │ books                │ 6+2     │ Book catalog (V4 added category) │")
    report.append("  │ magazines            │ 6+2     │ Magazine catalog                 │")
    report.append("  │ newspapers           │ 5+2     │ Newspaper catalog (NO category)  │")
    report.append("  │ borrow_records       │ 8+2     │ Core circulation (polymorphic FK)│")
    report.append("  │ audit_logs           │ 10+2    │ Activity logging                 │")
    report.append("  └──────────────────────┴─────────┴─────────────────────────────────┘")
    report.append("")

    report.append("=" * 70)
    report.append("  2. BORROW_RECORDS SCHEMA (Core Table)")
    report.append("=" * 70)
    report.append("")
    report.append("  Column            Type         Nullable  Notes")
    report.append("  ─────────────────────────────────────────────────────────────────")
    report.append("  id                BIGINT       NO        PK, auto-increment")
    report.append("  book_id           BIGINT       YES       FK -> books (nullable)")
    report.append("  magazine_id       BIGINT       YES       FK -> magazines (nullable)")
    report.append("  newspaper_id      BIGINT       YES       FK -> newspapers (nullable)")
    report.append("  student_id        BIGINT       YES       FK -> student_profiles")
    report.append("  borrower_name     VARCHAR(100) NO        Denormalized snapshot")
    report.append("  borrower_email    VARCHAR(100) NO        Denormalized snapshot")
    report.append("  borrower_phone    VARCHAR(20)  NO        Denormalized snapshot")
    report.append("  borrow_date       DATE         NO        Loan start date")
    report.append("  due_date          DATE         YES       Due date (V3 migration)")
    report.append("  return_date       DATE         YES       Return date (NULL=active)")
    report.append("  created_at        DATETIME(6)  NO        Audit timestamp")
    report.append("  updated_at        DATETIME(6)  NO        Audit timestamp")
    report.append("")
    report.append("  Design notes:")
    report.append("  - Polymorphic FK: exactly one of book/magazine/newspaper is set")
    report.append("  - student_id is nullable (walk-in borrows allowed)")
    report.append("  - due_date added in V3 — records before V3 may have NULL due_date")
    report.append("  - return_date=NULL means item is currently on loan")
    report.append("  - borrower_name/email/phone are snapshots at borrow time")
    report.append("")

    report.append("=" * 70)
    report.append("  3. LABEL FEASIBILITY")
    report.append("=" * 70)
    report.append("")
    report.append("  Frozen definition: label = 1 if return_date > effective_due_date")
    report.append("")
    report.append("  Canonical due-date semantics (OverdueCalculator):")
    report.append("    effective_due_date = due_date IF due_date IS NOT NULL")
    report.append("                       ELSE borrow_date + 14 days")
    report.append("")
    report.append("  Real-data label derivation:")
    report.append("    WHERE return_date IS NOT NULL  (completed loans only)")
    report.append("    AND   return_date > COALESCE(due_date, borrow_date + INTERVAL 14 DAY)")
    report.append("")
    report.append("  Status: FEASIBLE")
    report.append("  - borrow_date: NOT NULL, always available")
    report.append("  - due_date: NULLABLE, but OverdueCalculator handles NULL with +14 default")
    report.append("  - return_date: NULLABLE, only non-null for completed loans")
    report.append("  - Label can be derived identically to frozen pipeline")
    report.append("")

    report.append("=" * 70)
    report.append("  4. FEATURE MAPPING TABLE")
    report.append("=" * 70)
    report.append("")
    report.append("  Frozen Feature        │ Real-Data Source                           │ Avail? │ PIT?  │ Notes")
    report.append("  ──────────────────────┼────────────────────────────────────────────┼────────┼───────┼──────────────────────")
    report.append("  priorLoanCount        │ COUNT(borrow_records WHERE student_id=X    │ YES    │ YES   │ All data in borrow_records")
    report.append("                        │   AND borrow_date < current_borrow_date)  │        │       │")
    report.append("  priorOverdueCount     │ COUNT(completed loans WHERE student_id=X   │ YES    │ YES   │ Requires return_date")
    report.append("                        │   AND borrow_date < current AND overdue)  │        │       │")
    report.append("  historicalOverdueRate │ priorOverdueCount / priorLoanCount        │ YES    │ YES   │ Derived, 0 for first-time")
    report.append("  avgDaysToReturn       │ AVG(return_date - borrow_date)            │ YES    │ YES   │ Only from completed loans")
    report.append("                        │   for prior completed loans               │        │       │")
    report.append("  preferredCategory     │ Most common category from prior borrows   │ PARTIAL│ DEPENDS│ See category notes below")
    report.append("  daysSinceLastBorrow   │ MAX(borrow_date) for prior loans           │ YES    │ YES   │ -1 if no prior loans")
    report.append("  borrowDayOfWeek       │ DAYOFWEEK(borrow_date)                    │ YES    │ YES   │ Derived from borrow_date")
    report.append("  isWeekendBorrow       │ DAYOFWEEK(borrow_date) IN (1,7)           │ YES    │ YES   │ Derived from borrow_date")
    report.append("  semesterFactor        │ Academic period factor from borrow_date   │ YES    │ YES   │ Derived from month")
    report.append("  loanDuration          │ due_date - borrow_date                    │ YES    │ YES   │ V3 added due_date; NULL -> +14")
    report.append("  itemPopularityScore   │ COUNT(borrow_records WHERE item_id=X      │ YES    │ YES   │ Polymorphic FK (book/mag/newsp)")
    report.append("                        │   AND borrow_date < current_borrow_date)  │        │       │")
    report.append("  categoryOverdueRate   │ Overdue rate for item's category from     │ PARTIAL│ DEPENDS│ Depends on category availability")
    report.append("                        │   prior loans only                        │        │       │")
    report.append("")

    report.append("=" * 70)
    report.append("  5. CATEGORY COVERAGE AUDIT")
    report.append("=" * 70)
    report.append("")
    report.append("  Issue: Category availability varies by item type and migration history.")
    report.append("")
    report.append("  Item Type    │ Category Column │ Migration │ Status")
    report.append("  ─────────────┼─────────────────┼───────────┼──────────────────────────")
    report.append("  Books        │ VARCHAR(100)    │ V4        │ NULLABLE — pre-V4 books")
    report.append("  Magazines    │ VARCHAR(100)    │ V1        │ NULLABLE — may have NULLs")
    report.append("  Newspapers   │ NONE            │ N/A       │ NO CATEGORY COLUMN")
    report.append("")
    report.append("  Impact on frozen features:")
    report.append("  - preferredCategory: Cannot compute for newspapers (no category column)")
    report.append("  - categoryOverdueRate: Cannot compute for newspapers")
    report.append("  - Books added in V4: books created before V4 have NULL category")
    report.append("")
    report.append("  Recommended resolution:")
    report.append("  1. Newspapers: Use item type as fallback category ('Newspaper')")
    report.append("  2. NULL categories: Use 'Uncategorized' as fallback")
    report.append("  3. Document the category mapping strategy in Phase 5B")
    report.append("")

    report.append("=" * 70)
    report.append("  6. DUE_DATE AVAILABILITY AUDIT")
    report.append("=" * 70)
    report.append("")
    report.append("  Issue: due_date was added in V3 migration.")
    report.append("")
    report.append("  Records created BEFORE V3: due_date = NULL")
    report.append("  Records created AFTER V3:  due_date = borrow_date + 14 (or custom)")
    report.append("")
    report.append("  Impact on frozen features:")
    report.append("  - loanDuration: Can compute as COALESCE(due_date, borrow_date+14) - borrow_date")
    report.append("  - This matches the frozen OverdueCalculator semantics exactly")
    report.append("")
    report.append("  Status: FEASIBLE — NULL due_date handled by +14 default")
    report.append("")

    report.append("=" * 70)
    report.append("  7. DATA QUALITY CONCERNS")
    report.append("=" * 70)
    report.append("")
    report.append("  Potential issues to audit when real data exists:")
    report.append("")
    report.append("  Issue                          │ Detection Method")
    report.append("  ───────────────────────────────┼─────────────────────────────────────────")
    report.append("  Missing dates                  │ WHERE borrow_date IS NULL (should be 0)")
    report.append("  Invalid date ordering          │ WHERE due_date < borrow_date")
    report.append("  Return before borrow           │ WHERE return_date < borrow_date")
    report.append("  Duplicate loans                │ Same student + item + borrow_date")
    report.append("  Missing student references     │ WHERE student_id IS NULL (walk-ins)")
    report.append("  Missing item references        │ WHERE book_id IS NULL AND magazine_id")
    report.append("                                 │   IS NULL AND newspaper_id IS NULL")
    report.append("  Orphaned records               │ FK references non-existent entity")
    report.append("  Impossible durations           │ WHERE due_date - borrow_date > 365")
    report.append("  Future-dated records           │ WHERE borrow_date > CURRENT_DATE")
    report.append("  Single-loan students           │ Cannot compute borrower history features")
    report.append("")
    report.append("  Note: These checks must be implemented in Phase 5B when real data")
    report.append("  is available. Currently no real data exists to audit.")
    report.append("")

    report.append("=" * 70)
    report.append("  8. TEMPORAL SPLIT FEASIBILITY")
    report.append("=" * 70)
    report.append("")
    report.append("  Current status: CANNOT ASSESS — no real data exists.")
    report.append("")
    report.append("  When real data is available, the split should be determined by:")
    report.append("  1. Earliest and latest borrow_date in the dataset")
    report.append("  2. Sufficient sample size in both train and validation periods")
    report.append("  3. At least 6 months of validation data for temporal robustness")
    report.append("  4. The split boundary must be documented BEFORE training")
    report.append("")
    report.append("  Frozen principle: train on earlier loans, validate on later loans.")
    report.append("  The exact boundary (currently 2025-10-01 for synthetic data) should")
    report.append("  NOT be reused — it must be determined from the real data's range.")
    report.append("")

    report.append("=" * 70)
    report.append("  9. DATA LEAKAGE AUDIT")
    report.append("=" * 70)
    report.append("")
    report.append("  For each frozen feature, the leakage requirement is:")
    report.append("    feature_as_of_date == borrow_date of the current loan")
    report.append("    all source records have borrow_date < current loan's borrow_date")
    report.append("")
    report.append("  Feature                    │ Leakage Risk │ Mitigation")
    report.append("  ──────────────────────────┼──────────────┼─────────────────────────────")
    report.append("  priorLoanCount             │ LOW          │ Filter by borrow_date < current")
    report.append("  priorOverdueCount          │ LOW          │ Filter by borrow_date < current")
    report.append("  historicalOverdueRate      │ LOW          │ Derived from above two")
    report.append("  avgDaysToReturn            │ LOW          │ Only from completed prior loans")
    report.append("  preferredCategory          │ LOW          │ Only from prior borrows")
    report.append("  daysSinceLastBorrow        │ LOW          │ MAX(borrow_date) < current")
    report.append("  borrowDayOfWeek            │ NONE         │ Derived from current borrow_date")
    report.append("  isWeekendBorrow            │ NONE         │ Derived from current borrow_date")
    report.append("  semesterFactor             │ NONE         │ Derived from current borrow_date")
    report.append("  loanDuration               │ LOW          │ due_date set at checkout time")
    report.append("  itemPopularityScore        │ LOW          │ Filter by borrow_date < current")
    report.append("  categoryOverdueRate        │ LOW          │ Only from prior loans in category")
    report.append("")
    report.append("  Status: All 12 features can be computed without leakage using")
    report.append("  point-in-time filtering on borrow_date. No changes to the frozen")
    report.append("  feature definitions are required.")
    report.append("")

    report.append("=" * 70)
    report.append("  10. SCHEMA GAP: STUDENT_ID NULLABILITY")
    report.append("=" * 70)
    report.append("")
    report.append("  Issue: borrow_records.student_id is NULLABLE.")
    report.append("  Walk-in borrows without a registered student are allowed.")
    report.append("")
    report.append("  Impact on frozen features:")
    report.append("  - All 5 borrower-history features require student_id")
    report.append("  - Loans without student_id cannot be used for feature construction")
    report.append("")
    report.append("  Recommended resolution:")
    report.append("  - Exclude loans with student_id IS NULL from the ML dataset")
    report.append("  - Document the exclusion in Phase 5B")
    report.append("")

    report.append("=" * 70)
    report.append("  11. RECOMMENDATION")
    report.append("=" * 70)
    report.append("")
    report.append("  The frozen ML pipeline CANNOT be instantiated on real data today")
    report.append("  because no real historical data exists.")
    report.append("")
    report.append("  The correct next step is NOT Phase 5B (dataset construction).")
    report.append("  Instead:")
    report.append("")
    report.append("  1. DEPLOY the Libris application to production")
    report.append("  2. OPERATE it for several months to accumulate real circulation data")
    report.append("  3. THEN re-run this Phase 5A audit against the real database")
    report.append("  4. Proceed to Phase 5B only after real data passes the readiness checks")
    report.append("")
    report.append("  Timeline estimate:")
    report.append("  - Minimum: 3-6 months of real operation for meaningful ML evaluation")
    report.append("  - Ideal: 12+ months for temporal robustness analysis")
    report.append("")
    report.append("  During the waiting period:")
    report.append("  - The synthetic ML pipeline (Phases 3B-4F) remains frozen as benchmark")
    report.append("  - MODEL_SPECIFICATION.md remains the canonical reference")
    report.append("  - No model changes should be made until real data is available")
    report.append("")
    report.append("=" * 70)
    report.append("  VERDICT")
    report.append("=" * 70)
    report.append("")
    report.append("  Schema compatibility: GOOD — all 12 features can be mapped to real columns")
    report.append("  Label feasibility: GOOD — canonical overdue semantics reproduce exactly")
    report.append("  PIT safety: GOOD — all features computable before borrow_date")
    report.append("  Data availability: BLOCKED — no real historical data exists")
    report.append("")
    report.append("  RECOMMENDATION: Deploy Libris, operate for 3-12 months, then re-evaluate.")
    report.append("=" * 70)

    report_text = "\n".join(report)
    report_path = os.path.join(OUTPUT_DIR, "phase5a_readiness_report.txt")
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    with open(report_path, "w") as f:
        f.write(report_text + "\n")
    print(f"  Report written to {report_path}")
    print()
    print(report_text)
    print()
    print("Phase 5A COMPLETE.")


if __name__ == "__main__":
    main()
