package com.example.lms.controller;
import com.example.lms.dto.*; import com.example.lms.service.BookService; import io.swagger.v3.oas.annotations.Operation; import io.swagger.v3.oas.annotations.responses.ApiResponse; import io.swagger.v3.oas.annotations.responses.ApiResponses; import io.swagger.v3.oas.annotations.tags.Tag; import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.net.URI;
@RestController @RequestMapping("/api/books") @Tag(name="Books",description="Catalogue management for books")
public class BookController { private final BookService service; public BookController(BookService service){this.service=service;}
 @GetMapping @Operation(summary="List books",description="Paginated list with optional search by title or author.") public org.springframework.data.domain.Page<BookResponse> list(@RequestParam(required=false) String search,@RequestParam(required=false) String query, @RequestParam(defaultValue="0") int page, @RequestParam(defaultValue="10") int size){var q=query!=null?query:search;return service.list(q, org.springframework.data.domain.PageRequest.of(page, size));}
 @GetMapping("/{id}") @Operation(summary="Get book by ID") public BookResponse get(@PathVariable Long id){return service.get(id);}
 @PostMapping @Operation(summary="Create a book") @ApiResponse(responseCode="201",description="Book created") public ResponseEntity<BookResponse> create(@Valid @RequestBody BookRequest request){var created=service.create(request);return ResponseEntity.created(URI.create("/api/books/"+created.id())).body(created);}
 @PutMapping("/{id}") @Operation(summary="Update a book") public BookResponse update(@PathVariable Long id,@Valid @RequestBody BookRequest request){return service.update(id,request);}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @Operation(summary="Delete a book") @ApiResponse(responseCode="204",description="Book deleted") public void delete(@PathVariable Long id){service.delete(id);}
}
